theme: jekyll-theme-slate
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter_opts:
    disable: true
title: Computer science conferences: Double-blind status
description: Foo
author:
  name: Emery Berger

